BEGIN TRANSACTION;


CREATE TABLE ENDERECO(
CODIGOENDERECO INT NOT NULL,
DECRICAOLOGRADOURO VARCHAR(150) NOT NULL,
PRIMARY KEY(CODIGOENDERECO));


CREATE TABLE TELEFONE (
CODIGOTELEFONE INT NOT NULL,
NROTELEFONE VARCHAR(20) NOT NULL,
NROCELULAR VARCHAR(20),
PRIMARY KEY(CODIGOTELEFONE));


CREATE TABLE DEPARTAMENTO (
CODIGODEPARTAMENTO INT NOT NULL,
NOMEDEPTO VARCHAR(150) NOT NULL,
LOCALIZACAODEPTO VARCHAR(100) NOT NULL,
CODPROFRESP VARCHAR(16) NOT NULL,
PRIMARY KEY(CODIGODEPARTAMENTO));


CREATE TABLE AGENCIACONTABANCARIA (
CODIGOAGENCIA INT NOT NULL,
CODIGOENDERECOAGENCIA INT NOT NULL, 
NUMEROAGENCIA INT NOT NULL,
CODIGOCONTABANCARIA INT,
PRIMARY KEY(CODIGOAGENCIA),
FOREIGN KEY (CODIGOENDERECOAGENCIA) REFERENCES ENDERECO(CODIGOENDERECO));



CREATE TABLE CURSOGRADUACAO (
CODIGOCURSOGRADUACAO INT NOT NULL,
NOMECURSO VARCHAR(100) NOT NULL,
DATACRIACAO DATETIME ,
NROREVISAO VARCHAR(30),
DEPTORESP INT NOT NULL,
PRIMARY KEY(CODIGOCURSOGRADUACAO),
FOREIGN KEY (DEPTORESP) REFERENCES DEPARTAMENTO (CODIGODEPARTAMENTO));


CREATE TABLE ALUNO  (
CPFALUNO VARCHAR(16) NOT NULL,
NOMEALUNO VARCHAR(100) NOT NULL,
EMAILALUNO VARCHAR(100),
CODENDERECOALUNO INT NOT NULL, 
NUMEROENDERECO INT NOT NULL,
CODIGOCURSO1 INT,
ANOCURSO1 INT,
CODIGOCURSO2 INT,
ANOCURSO2 INT,
SEMESTRECURSO1 INT, 
SEMESTRECURSO2 INT,
PRIMARY KEY (CPFALUNO),
FOREIGN KEY (CODENDERECOALUNO) REFERENCES ENDERECO(CODIGOENDERECO));



CREATE TABLE PROFESSOR (
CPFPROFESSOR VARCHAR(16) NOT NULL,
NOMEPROFESSOR VARCHAR(16) NOT NULL,
CODENDERPROFESSOR INT NOT NULL,
EMAILPROFESSOR VARCHAR(100),
TELEFONEPROFESSOR INT,
SALARIOPROFESSOR REAL,
CODIGOCONTA INT,
DIGITOCONTA INT,
NIVELESCOLARIDADE VARCHAR(100),
CODIGODEPARTAMENTO VARCHAR(16) NOT NULL,
PRIMARY KEY(CPFPROFESSOR),
FOREIGN KEY (CODENDERPROFESSOR) REFERENCES ENDERECO (CODIGOENDERECO),
FOREIGN KEY (CODIGODEPARTAMENTO) REFERENCES DEPARTAMENTO (CPFPROFESSOR),
FOREIGN KEY (CODIGOCONTA) REFERENCES AGENCIACONTABANCARIA (CODIGOCONTABANCARIA));



CREATE TABLE DISCIPLINASGRADUCAO (
CODDISCIPLINA VARCHAR(10) NOT NULL,
NOMEDISCIPLINA VARCHAR(30) NOT NULL,
EMANTADISCIPLINA VARCHAR(5000),
CARGAHORARIADISCIPLINA VARCHAR(25),
SEMESTRE INT,
CODDPTO INT NOT NULL,
PRIMARY KEY(CODDISCIPLINA),
FOREIGN KEY (CODDPTO) REFERENCES DEPARTAMENTO(CODIGODEPARTAMENTO));



CREATE TABLE DISCIPLINASOBRIGATORIASCURSO (
CODIGODISCIPLINA INT NOT NULL,
CODIGOCURSOGRADUACAO INT NOT NULL,
PRIMARY KEY (CODIGODISCIPLINA));


CREATE TABLE DISCIPLINASOPTATIVASCURSO (
CODCURSOGRADUACAO INT NOT NULL,
CODIGODISCIPLINA INT NOT NULL,
PRIMARY KEY (CODIGODISCIPLINA));



CREATE TABLE DISCIPLINASOFERTADASCURSO (
CODIGODISCIPLINACURSO INT NOT NULL,
CODIGOCURSO INT NOT NULL,
PERIODOLETIVO INT,
PRIMARY KEY (CODIGODISCIPLINACURSO));



CREATE TABLE TURMA (
SEMESTRETURMA INT NOT NULL,
ANOTURMA INT NOT NULL,
CODDISCIPLINA VARCHAR(10) NOT NULL,
CODIGOPROFESSOR VARCHAR(16) NOT NULL,
HORARIOTURMA VARCHAR(30),
CODCURSOGRADUACAO INT NOT NULL,
CODIGOTURMA INT NOT NULL,
PRIMARY KEY(CODIGOTURMA),
FOREIGN KEY (CODDISCIPLINA) REFERENCES DISCIPLINASGRADUACAO (CODDISCIPLINA));



CREATE TABLE ALUNOSMATRICULADOS (
CODIGOTURMA INT NOT NULL,
CPFALUNO VARCHAR(16) NOT NULL,
NOTAALUNO REAL,
PERCENTUALFREQ REAL,
FLGTRANCAMENTOGERAL BOOLEAN DEFAULT 'F',
PRIMARY KEY (CPFALUNO,CODIGOTURMA),
FOREIGN KEY (CPFALUNO) REFERENCES ALUNO (CPFALUNO),
FOREIGN KEY (CODIGOTURMA) REFERENCES TURMA (CODIGOTURMA));








