BEGIN TRANSACTION;


CREATE TABLE ENDERECO (
CODIGOENDERECO INT NOT NULL, 
DESCRICAOENDERECOLOGRADOURO VARCHAR(150) NOT NULL,
COMPLEMENTOENDERECO VARCHAR(30),
PRIMARY KEY (CODIGOENDERECO));

CREATE TABLE TELEFONE (
CODIGOTELEFONE INT NOT NULL,
NUMEROTELEFONE VARCHAR(30) NOT NULL,
PRIMARY KEY (CODIGOTELEFONE) );


CREATE TABLE MEMBRO (
NUMMEMBRO INT NOT NULL,
NOMEMEMBRO VARCHAR(150) NOT NULL,
EMAILMEMBRO VARCHAR(100),
SENHAMEMBRO VARCHAR(20),
CODIGOENDERECOMEMBRO INT NOT NULL,
NUMEROENDERECOMEMBRO INT,
CODIGOTELEFONEMEBRO INT NOT NULL,
PRIMARY KEY	(NUMMEMBRO),
FOREIGN KEY (CODIGOENDERECOMEMBRO) REFERENCES ENDERECO(CODIGOENDERECO),
FOREIGN KEY	(CODIGOTELEFONEMEBRO) REFERENCES TELEFONE(CODIGOTELEFONE));

CREATE TABLE COMPRA (
NUMMEMBRO INT NOT NULL,
NUMCONTA INT,
NUMENCAMINHAMENTOCOMPRA INT NOT NULL,
PRIMARY KEY(NUMENCAMINHAMENTOCOMPRA));


CREATE TABLE VENDA (
NUMMEMBRO INT NOT NULL,
NUMCONTA INT,
NUMENCAMINHAMENTOVENDA INT NOT NULL,
PRIMARY KEY(NUMENCAMINHAMENTOVENDA));


CREATE TABLE CLASSIFICACAO (
CODIGOCLASSIFICACAO INT NOT NULL,
DESCRICAOCLASSIFICACAO VARCHAR(300) NOT NULL,
PRIMARY KEY (CODIGOCLASSIFICACAO));


CREATE TABLE ITEM (
NUMMEMBRO INT NOT NULL,
CODIGOITEM INT NOT NULL,
TITULOITEM VARCHAR(300) NOT NULL,
DESCRICAOITEM VARCHAR(300) NOT NULL,
PRECOINICIALITEM REAL NOT NULL,
PRECOINCREMENTADOITEM REAL,
DATAINICIOLEILAO DATETIME NOT NULL, 
DATAFIMLEILAO DATETIME,
CLASSIFICACAOITEM INT NOT NULL,
PRIMARY KEY (CODIGOITEM),
FOREIGN KEY (CLASSIFICACAOITEM) REFERENCES CLASSIFICACAO(CODIGOCLASSIFICACAO));


CREATE TABLE LANCE (
CODIGOITEM INT NOT NULL,
CODIGOLANCE INT NOT NULL,
VALORLANCE REAL NOT NULL,
DATALANCE DATETIME NOT NULL,
PRIMARY KEY(CODIGOLANCE));



CREATE TABLE TRANSACAO (
NUMMEMBRO1 INT NOT NULL,
NUMMEMBRO2 INT NOT NULL,
CODIGOTRANSACAO INT NOT NULL,
DATAPGTO DATETIME,
CODIGOENDERECO INT NOT NULL,
CODIGONOTA INT,
PRIMARY KEY (CODIGOTRANSACAO),
FOREIGN KEY (CODIGOENDERECO) REFERENCES ENDERECO(CODIGOENDERECO),
FOREIGN KEY (NUMMEMBRO1) REFERENCES MEMBRO (NUMMEMBRO),
FOREIGN KEY (NUMMEMBRO2) REFERENCES MEMBRO (NUMMEMBRO));



CREATE TABLE NOTA (
CODIGONOTA INT NOT NULL,
NOTAFISCAL VARCHAR(20) NOT NULL,
DESCRICAOPRODUTONOTA VARCHAR(50) NOT NULL,
CODIGOTRANSACAO INT NOT NULL,
PRIMARY KEY(CODIGONOTA),
FOREIGN KEY (CODIGOTRANSACAO) REFERENCES TRANSACAO(CODIGOTRANSACAO));



CREATE TABLE REGISTRONOTA (
CODIGONOTA INT NOT NULL,
PONTUACAO REAL NOT NULL,
PRIMARY KEY(CODIGONOTA),
CHECK (PONTUACAO < 10));




