BEGIN TRANSACTION;


CREATE TABLE ENDERECO (
CODIGOENDERECO INT NOT NULL, 
DESCRICAOENDERECOLOGRADOURO VARCHAR(150) NOT NULL,
COMPLEMENTOENDERECO VARCHAR(30),
PRIMARY KEY (CODIGOENDERECO));


CREATE TABLE TONALIDADE (
IDTONALIDADE INT NOT NULL,
DESCRICAOTONALIDADE VARCHAR(20) NOT NULL,
ALTURATONALIDADE VARCHAR(30),
PRIMARY KEY (IDTONALIDADE),
CHECK (ALTURATONALIDADE IN ('MAIOR', 'MENOR', 'SUSTENIDO', 'BEMOL', 'MENOR7', 'MAIOR7', 'DIMINUTO','OUTRA')));


CREATE TABLE PROFISSIONAL (
TIPOPROFISSIONAL VARCHAR(30) NOT NULL,
CPFPROFISSIONAL VARCHAR(16) NOT NULL,
CODIGOENDERECO INT NOT NULL,
NUMEROENDERECOPROFISSIONAL INT NOT NULL,
NOMEPROFISSIONAL VARCHAR(150) NOT NULL,
TELEFONEPROFISSIONAL VARCHAR(20),
PRIMARY KEY(CPFPROFISSIONAL),
FOREIGN KEY (CODIGOENDERECO)REFERENCES ENDERECO(CODIGOENDERECO),
CHECK (TIPOPROFISSIONAL IN ('MUSICO','COMPOSITOR','musico','compositor')));


CREATE TABLE INSTRUMENTO (
IDINSTURMENTO INT NOT NULL,
NOMEINSTRUMENTO VARCHAR(100) NOT NULL,
IDTONALIDADE INT NOT NULL,
PRIMARY KEY(IDINSTURMENTO),
FOREIGN KEY (IDTONALIDADE) REFERENCES TONALIDADE(IDTONALIDADE) );


CREATE TABLE FORMATOALBUM (
CODIGOFORMATO INT NOT NULL,
DESCRICAOFORMATO VARCHAR(250) NOT NULL,
PRIMARY KEY(CODIGOFORMATO));

CREATE TABLE MUSICA (
IDMUSICA INT NOT NULL,
TITULOMUSICA VARCHAR(150) NOT NULL,
CPFCOMPOSITOR VARCHAR(16) NOT NULL,
PRIMARY KEY (IDMUSICA));

CREATE TABLE  MUSICAARTISTACD (
CODIGOCD INT NOT NULL,
DESCRICAOTITULOMUSICA VARCHAR(150) NOT NULL,
CODIGOMUSICA INT NOT NULL,
IDMUSICA INT NOT NULL,
PRIMARY KEY(CODIGOMUSICA),
FOREIGN KEY(IDMUSICA) REFERENCES MUSICA(IDMUSICA));


CREATE TABLE ALBUM (
IDALBUM INT NOT NULL,
TITULOALBUM VARCHAR(150) NOT NULL,
DATADIREITOSALBUM DATETIME,
CODIGOFORMATO INT,
IDMUSICA INT,
PRIMARY KEY(IDALBUM),
FOREIGN KEY (IDMUSICA) REFERENCES MUSICAARTISTA(CODIGOMUSICA));


CREATE TABLE CDALBUMARTISTA (
CPFPROFISSIONAL VARCHAR(16) NOT NULL,
IDALBUM INT NOT NULL,
CODIGOCD INT NOT NULL,
CODIGOMUSICA INT,
PRIMARY KEY(CODIGOCD),
FOREIGN KEY (IDALBUM) REFERENCES ALBUM(IDALBUM));



CREATE TABLE COMPOSITORES (
CPFCOMPOSITOR VARCHAR(16) NOT NULL,
IDMUSICA INT NOT NULL,
PRIMARY KEY(CPFCOMPOSITOR, IDMUSICA),
FOREIGN KEY (IDMUSICA) REFERENCES MUSICA(IDMUSICA));



CREATE TABLE INTERPRETACAOMUSICA (
CPFPROFISSIONAL VARCHAR(16) NOT NULL,
IDALBUM INT NOT NULL,
IDMUSICA INT NOT NULL,
IDINSTURMENTO INT NOT NULL,
IDINTERPRETACAO INT NOT NULL,
PRIMARY KEY(IDINTERPRETACAO),
FOREIGN KEY (IDMUSICA) REFERENCES MUSICA(IDMUSICA),
FOREIGN KEY (IDALBUM) REFERENCES ALBUM(IDALBUM));



CREATE TABLE MUSICOINSTRUMENTO (
CPFPROFISSIONAL VARCHAR(16) NOT NULL,
IDINSTURMENTO INT NOT NULL,
IDMUSICOINSTRUMENTO INT NOT NULL,
PRIMARY KEY(IDMUSICOINSTRUMENTO),
FOREIGN KEY (IDINSTURMENTO) REFERENCES INSTRUMENTO(IDINSTURMENTO));


CREATE TABLE PRODUTORAALBUM (
IDPRODUCAO INT NOT NULL,
IDALBUM INT NOT NULL,
CPFPROFISSIONAL VARCHAR(16) NOT NULL,
PRIMARY KEY(IDPRODUCAO),
FOREIGN KEY (CPFPROFISSIONAL) REFERENCES PROFISSIONAL (CPFPROFISSIONAL));








