BEGIN TRANSACTION;

CREATE TABLE HANGAR(
IDHANGAR INT NOT NULL,
CAPACIDADEHANGAR INT NOT NULL,
LOCALHANGAR VARCHAR(50),
PRIMARY KEY(IDHANGAR));


CREATE TABLE AERONAVE (
IDAERO INT NOT NULL,
TIPOAERO VARCHAR(40) NOT NULL,
IDHANGAR INT,
PRIMARY KEY(IDAERO));


CREATE TABLE TIPOAERONAVE (
IDAERO INT NOT NULL,
MODELOAERO VARCHAR(50) NOT NULL,
CAPACIDADEAERO INT NOT NULL,
PESOAERO REAL,
PRIMARY KEY(IDAERO));


CREATE TABLE TIPORESTRICOOES (
CODRESTRICAO INT NOT NULL,
DESCRICAORESTRICAO VARCHAR(500) NOT NULL,
PRIMARY KEY(CODRESTRICAO));


CREATE TABLE TIPOLICENCAS (
CODIGOLICENCA INT NOT NULL,
DESCRICAOLICENCA VARCHAR(500) NOT NULL,
PRIMARY	KEY(CODIGOLICENCA));


CREATE TABLE TELEFONE (
CODIGOTELEFONE INT NOT NULL,
NUMEROTELEFONE VARCHAR(20) NOT NULL,
NUMEROCELULAR VARCHAR(20),
PRIMARY KEY(CODIGOTELEFONE,NUMEROTELEFONE));


CREATE TABLE ENDERECO (
DESCRICAOENDERECOLOGRADOURO VARCHAR(100) NOT NULL,
CODIGOENDERECO INT NOT NULL,
PRIMARY KEY(CODIGOENDERECO));



CREATE TABLE PILOTO (
CPFPILOTO VARCHAR(16) NOT NULL,
NOMEPILOTO VARCHAR(100) NOT NULL,
CODIGOENDERECO INT NOT NULL,
NUMEROLOGRADOURO INT NOT NULL,
CODIGOTELEFONE INT,
CODRESTRICAO INT,
CODIGOLICENCA INT,
PRIMARY KEY(CPFPILOTO),
FOREIGN KEY(CODRESTRICAO) REFERENCES TIPORESTRICOOES(CODRESTRICAO),
FOREIGN KEY(CODIGOLICENCA) REFERENCES TIPOLICENCAS(CODIGOLICENCA));


CREATE TABLE FUNCIONARIO (
CPFFUNCIONARIO VARCHAR(16) NOT NULL,
NOMEFUNCIONARIO VARCHAR(150) NOT NULL,
CODIGOENDERECOFUNCIONARIO INT NOT NULL,
CODIGOTELEFONE INT NOT NULL,
CODIGOENDERECO INT,
NUMEROLOGRADOURO INT,
SALARIOFUNCIONARIO REAL,
TURNOTRABALHOFUNCIONARIO VARCHAR(30),
PRIMARY KEY(CPFFUNCIONARIO),
FOREIGN KEY(CODIGOTELEFONE) REFERENCES TELEFONE(CODIGOTELEFONE),
FOREIGN KEY(CODIGOENDERECO) REFERENCES ENDERECO(CODIGOENDERECO) );



CREATE TABLE SERVICOMANUTENCAO (
IDAERO INT NOT NULL,
IDMANUTENCAO INT NOT NULL,
DATAMANUTENCAO DATETIME NOT NULL,
NUMEROHORASGASSTAS REAL,
TIPOMANUT VARCHAR(50),
PRIMARY KEY(IDMANUTENCAO, DATAMANUTENCAO));



CREATE TABLE PARTICIPANTESMANUTENCAO (
CPFFUNCIONARIO VARCHAR(16) NOT NULL,
IDMANUTENCAO INT NOT NULL,
DESCRICAOSERVICO VARCHAR(500) NOT NULL,
IDPARTICIPANTE INT NOT NULL,
PRIMARY KEY(IDPARTICIPANTE),
FOREIGN KEY(CPFFUNCIONARIO) REFERENCES FUNCIONARIO(CPFFUNCIONARIO));



CREATE TABLE TIPOAEROPERMISSAOPILOTO (
IDTIPO INT NOT NULL,
IDAERO INT NOT NULL,
CPFPILOTO VARCHAR(16) NOT NULL,
PRIMARY KEY(IDTIPO));


CREATE TABLE TIPOAEROPERMISSAOMANUTENCAO (
IDTIPOMANUNTENCAO INT NOT NULL, 
CPFFUNCIONARIO VARCHAR(16) NOT NULL, 
PRIMARY KEY(IDTIPOMANUNTENCAO));


CREATE TABLE SERVICOMANUTENCAODESCRICAOSERVICO (
IDSERVICO INT NOT NULL,
CPFFUNCIONARIO VARCHAR(16) NOT NULL,
IDTIPOMANUNTENCAO INT NOT NULL,
PRIMARY KEY(IDSERVICO));


CREATE TABLE PROPRIETARIOAVIAO (
DATACOMPRAAVIAOO DATETIME,
CPFPROPRIETARIOAVIAO VARCHAR(16) NOT NULL,
IDAERO INT NOT NULL,
IDPROPRIETARIO INT NOT NULL,
PRIMARY KEY(IDPROPRIETARIO));




